set_property PACKAGE_PIN U20 [get_ports SCK_H]
set_property PACKAGE_PIN R19 [get_ports SCK_L]
set_property PACKAGE_PIN W20 [get_ports SD_H]
set_property PACKAGE_PIN T19 [get_ports SD_L]
set_property PACKAGE_PIN T20 [get_ports WS_H]
set_property PACKAGE_PIN N20 [get_ports WS_L]
set_property IOSTANDARD LVCMOS33 [get_ports SCK_H]
set_property IOSTANDARD LVCMOS33 [get_ports SCK_L]
set_property IOSTANDARD LVCMOS33 [get_ports SD_H]
set_property IOSTANDARD LVCMOS33 [get_ports SD_L]
set_property IOSTANDARD LVCMOS33 [get_ports WS_H]
set_property IOSTANDARD LVCMOS33 [get_ports WS_L]
set_property DRIVE 12 [get_ports SCK_H]
set_property DRIVE 12 [get_ports SCK_L]
set_property DRIVE 12 [get_ports WS_H]
set_property DRIVE 12 [get_ports WS_L]
set_property SLEW FAST [get_ports SCK_H]
set_property SLEW FAST [get_ports SCK_L]
set_property SLEW FAST [get_ports WS_H]
set_property SLEW FAST [get_ports WS_L]
set_property PULLDOWN true [get_ports SD_H]
set_property PULLDOWN true [get_ports SD_L]

set_property PACKAGE_PIN P20 [get_ports wave]
set_property IOSTANDARD LVCMOS33 [get_ports wave]

set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

